spring:
    application:
        name: payment-log-service
    profiles:
        active: microservice, dbconfig
    config:
        import: configserver:http://localhost:8888
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: payment-logs