spring:
    application:
        name: administration-service
    profiles:
        active: microservice, dbconfig
    config:
        import: configserver:http://localhost:8888
    kafka:
        bootstrap-servers: localhost:9092