spring:
    application:
        name: email-service
    profiles:
        active: microservice
    config:
        import: configserver:http://localhost:8888
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: email
    mail:
        host: smtp.yandex.ru
        port: 465
        username: secret
        password: secret
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    ssl:
                        enable: true
                transport:
                    protocol: smtps
        protocol: smtps